version: '3.11.5'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: mysql:8-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/mysql/data
    restart: on-failure
    ports:
      - "3306:3306"
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata: